name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.17.0"

dependencies:
  bloc: ^8.1.4
  conditional_builder_null_safety: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
